version: '3.7'

services:
  app: 
    image: apc91/ms-flights-api-gateway:1.0.0
    container_name: app_vuelos
    env_file: .env
    ports: 
      - 80:3000
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks: 
      - ms_nestjs

  microservice-flights: 
    image: apc91/microservice-flights:1.0.0
    container_name: microservice-flights
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks: 
        - ms_nestjs

  microservice-passengers: 
    image: apc91/microservice-passengers:1.0.0
    container_name: microservice-passengers
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks: 
      - ms_nestjs

  microservice-users: 
    image: apc91/microservice-users:1.0.0
    container_name: microservice-users
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks: 
      - ms_nestjs

  mongodb:
    image: mongo:5.0.16
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - ms_nestjs

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    restart: always
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - ms_nestjs

volumes:
  mongodb: 

networks:
  ms_nestjs:
